#define B1_Pin GPIO_PIN_13
#define B1_GPIO_Port GPIOC
#define B1_EXTI_IRQn EXTI15_10_IRQn
#define Mybutton_Pin GPIO_PIN_0
#define Mybutton_GPIO_Port GPIOC
#define Mybutton_EXTI_IRQn EXTI0_IRQn
#define Reddiode_Pin GPIO_PIN_1
#define Reddiode_GPIO_Port GPIOC
#define USART_TX_Pin GPIO_PIN_2
#define USART_TX_GPIO_Port GPIOA
#define USART_RX_Pin GPIO_PIN_3
#define USART_RX_GPIO_Port GPIOA
#define GreenDiode_Pin GPIO_PIN_4
#define GreenDiode_GPIO_Port GPIOA
#define LD2_Pin GPIO_PIN_5
#define LD2_GPIO_Port GPIOA
#define BlueDiode_Pin GPIO_PIN_0
#define BlueDiode_GPIO_Port GPIOB
#define TMS_Pin GPIO_PIN_13
#define TMS_GPIO_Port GPIOA
#define TCK_Pin GPIO_PIN_14
#define TCK_GPIO_Port GPIOA
#define SWO_Pin GPIO_PIN_3
#define SWO_GPIO_Port GPIOB
